#!/bin/busybox sh
# check

dir="$1";
if [ -z "$dir" ];
then
	echo "$0: output directory required !" >&2;
	exit 1;
fi;

# cleanup old
find "$dir" -mtime +3 -type f | xargs rm -f

# generate new
date=`date "+%Y-%m-%d-%H"`;
out="$dir/$date";
fail=;

# check
cd "$0.d" || exit;

# some variables
export UPCHECK_WEEKNUM=`date +%W`;
export UPCHECK_WEEKDAY=`date +%w`;
export UPCHECK_HOUR=`date +%H`;
export UPCHECK_MIN=`date +%M`;
export UPCHECK_UNIX=`date +%s`;
export UPCHECK_UTC_UNIX=`date -u +%s`;

# upcheck once a day
# not realy once, but not whole day because we don't know when remote uptime check comes
export UPCHECK_ONCE;
if [ "$UPCHECK_HOUR" -eq 3 -a "$UPCHECK_MIN" -lt 15 ];
then
	UPCHECK_ONCE=1;
fi;

# generate output file
rm -f "$out";
touch "$out";

date "+%Y-%m-%d %H:%M:%S" >$out;
for i in *;
do
	[ -x "$i" ] || continue;
	name="${i#*-}";

	./$i 2>&1 >>$out;
	if [ $? -eq 0 ];
	then
		echo "$name OK" >>$out;
	else
		echo "$name FAILED" >>$out;
		fail=1;
	fi;
done;

# ALL OK
[ -z "$fail" ] && echo "ALL OK" >>$out;
