#!/bin/busybox sh
# check

dir="$1";
if [ -z "$dir" ];
then
	echo "$0: output directory required !" >&2;
	exit 1;
fi;

[ -e "$0.conf" ] && source "$0.conf";

# generate new
date=`date "+%Y-%m-%d-%H"`;
out="$dir/$date";
fail=;

# check
cd "$0.d" || exit;

# some variables
export UPCHECK_WEEKNUM=`date +%W`;
export UPCHECK_WEEKDAY=`date +%w`;
export UPCHECK_HOUR=`date +%H`;
export UPCHECK_MIN=`date +%M`;
export UPCHECK_UNIX=`date +%s`;
export UPCHECK_UTC_UNIX=`date -u +%s`;

# cleanup old
[ "$UPCHECK_HOUR" = "23" ] && find "$dir" -mtime +7 -type f | xargs rm -f

# upcheck once a day
# not realy once, but not whole day because we don't know when remote uptime check request comes
export UPCHECK_ONCE;
if [ "$UPCHECK_HOUR" -eq 3 -a "$UPCHECK_MIN" -gt 45 ];
then
	UPCHECK_ONCE=1;
fi;

# upcheck once a hour
# not realy once, but not whole hour because we don't know when remote uptime check request comes
export UPCHECK_ONCE_HOUR;
if [ "$UPCHECK_MIN" -ge 50 ];
then
	UPCHECK_ONCE_HOUR=1;
fi;

# generate output file
if [ -e "$out" ] && ! grep -q "ALL OK" "$out";
then
	mv "$out" "$out-fail";
fi;
rm -f "$out";
touch "$out";

date -u "+%Y-%m-%d %H:%M:%S %Z%z" >$out;
uptime | sed -e 's/^ */uptime: /g' >>$out;
for i in *;
do
	[ -x "$i" ] || continue;
	name="${i#*-}";
	bname=`echo "${name%.*}" | sed -e 's:-:_:g'`;

	# no check
	disabled=`echo "\\${UPCHECK_NO_CHECK_$bname}"`;
	disabled=`eval echo "$disabled"`;
	[ -n "$disabled" ] && continue;

	./$i 2>&1 >>$out;
	if [ $? -eq 0 ];
	then
		echo "$name OK" >>$out;
	else
		echo "$name FAILED" >>$out;
		fail=1;
	fi;
done;

# ALL OK
[ -z "$fail" ] && echo "ALL OK" >>$out;
